### ISSUE TITLE
Cannot clone the submodule external/Visual_Speech_Recognition_for_Multiple_Languages

### ISSUE THREAD

**Issue by ilysenkov** [filby89/spectre#1]
Hi,

This repo contains a submodule with url [https://github.com/filby89/Visual_Speech_Recognition_for_Multiple_Languages.git](https://github.com/filby89/Visual_Speech_Recognition_for_Multiple_Languages.git), but there is no public repository with such url.

So the command `git clone --recurse-submodules -j4 https://github.com/filby89/spectre` fails and it is not possible to run the demo, because it fails when trying to import `FaceTracker` from `external.Visual_Speech_Recognition_for_Multiple_Languages.tracker.face_tracker`.

Could you please look into that?

**Comment by filby89** [comment]
Hi,
thanks, I deleted my fork of the submodule but forgot to update the submodule link. I have now commited the correct submited. If you dont want to reclone the entire repo, the correct submodule is https://github.com/mpc001/Visual_Speech_Recognition_for_Multiple_Languages.

Let me know if the problem is fixed.

**Comment by iamgmujtaba** [comment]
Thank you for the update. 
I am getting the following error while running this command. 
`python demo.py --input samples/LRS3/0Fi83BHQsMA_00002.mp4 --audio`


I have used the following commands during installation.
`git clone --recurse-submodules -j4 https://github.com/filby89/spectre`
`conda create -n spectre python=3.8 -y`
`conda activate spectre`
`conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch -y`
`conda install -c conda-forge -c fvcore fvcore iopath -y`
`conda install pytorch3d -c pytorch3d -y`
`pip install -r requirements.txt `
`cd /external/face_alignment/`
`pip install -e .`
`cd ../face_detection/`
`pip install -e .`
`cd ../..`
`pip install gdown`
`bash quick_install.sh `


Using cache found in /home/paul/.cache/torch/hub/pytorch_vision_v0.8.1
An exception occurred in telemetry logging.Disabling telemetry to prevent further exceptions.
Traceback (most recent call last):
  File "/home/paul/anaconda3/envs/spectre/lib/python3.8/site-packages/iopath/common/file_io.py", line 946, in __log_tmetry_keys
    handler.log_event()
  File "/home/paul/anaconda3/envs/spectre/lib/python3.8/site-packages/iopath/common/event_logger.py", line 97, in log_event
    del self._evt
AttributeError: _evt
Traceback (most recent call last):
  File "demo.py", line 231, in <module>
    main(parser.parse_args())
  File "demo.py", line 94, in main
    image_paths, landmarks, videofolder, fps = extract_frames(args.input, detect_landmarks=args.crop_face)
  File "demo.py", line 28, in extract_frames
    face_tracker = FaceTracker()
  File "/media/paul/data/spectre/external/Visual_Speech_Recognition_for_Multiple_Languages/tracker/face_tracker.py", line 23, in __init__
    self.face_detector = RetinaFacePredictor(
  File "/media/paul/data/spectre/external/face_detection/ibug/face_detection/retina_face/retina_face_predictor.py", line 28, in __init__
    pretrained_dict = torch.load(model.weights, map_location=self.device)
  File "/home/paul/anaconda3/envs/spectre/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/paul/anaconda3/envs/spectre/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by iamgmujtaba** [comment]
Solved these issues by using the following commands. I have to install [git-lfs](https://stackoverflow.com/questions/48734119/git-lfs-is-not-a-git-command-unclear) before installing face_detection.
`curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash`
`sudo apt-get install git-lfs`

Then use the following commands for the installation
`cd face_detection`
`git lfs pull`
`pip install -e .`

**Comment by ilysenkov** [comment]
@filby89, thank you for the quick fix! Everything is working now)
