### ISSUE TITLE
Can not find the run_av_hubert.sh file

### ISSUE THREAD

**Issue by shuishiwojiade** [filby89/spectre#10]
Thanks for your great works. At the end of Readme, you pointed out the test command in the LRS3 dataset. But I can not find the script named run_av_hubert.sh. So how do I verify the performance of the model in lipreading？

**Comment by filby89** [comment]
Hi, there is a mistake in the README file. You need to run 
```bash
python utils/run_av_hubert.py --videos "logs/test_videos_000000/*_mouth.avi --LRS3_path data/LRS3"
```
