### ISSUE TITLE
script demo.py fail to start

### ISSUE THREAD

**Issue by razvanab** [filby89/spectre#15]
python demo.py --input samples/LRS3/0Fi83BHQsMA_00002.mp4 --audio

Downloading: "https://github.com/pytorch/vision/archive/v0.8.1.zip" to /home/user/.cache/torch/hub/v0.8.1.zip
/home/user/miniconda3/envs/spectre/lib/python3.8/site-packages/chumpy/__init__.py:11: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  from numpy import bool, int, float, complex, object, unicode, str, nan, inf
/home/user/miniconda3/envs/spectre/lib/python3.8/site-packages/chumpy/__init__.py:11: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  from numpy import bool, int, float, complex, object, unicode, str, nan, inf
/home/user/miniconda3/envs/spectre/lib/python3.8/site-packages/chumpy/__init__.py:11: FutureWarning: In the future `np.str` will be defined as the corresponding NumPy scalar.
  from numpy import bool, int, float, complex, object, unicode, str, nan, inf
Traceback (most recent call last):
  File "demo.py", line 231, in <module>
    main(parser.parse_args())
  File "demo.py", line 91, in main
    spectre = SPECTRE(spectre_cfg, args.device)
  File "/home/user/dev/face_stuff/spectre/src/spectre.py", line 38, in __init__
    self._create_model(self.cfg.model)
  File "/home/user/dev/face_stuff/spectre/src/spectre.py", line 73, in _create_model
    self.flame = FLAME(model_cfg).to(self.device)
  File "/home/user/dev/face_stuff/spectre/src/models/FLAME.py", line 47, in __init__
    ss = pickle.load(f, encoding='latin1')
  File "/home/user/miniconda3/envs/spectre/lib/python3.8/site-packages/chumpy/__init__.py", line 11, in <module>
    from numpy import bool, int, float, complex, object, unicode, str, nan, inf
ImportError: cannot import name 'bool' from 'numpy' (/home/user/miniconda3/envs/spectre/lib/python3.8/site-packages/numpy/__init__.py)

**Comment by filby89** [comment]
I believe this is something to do with your numpy version. Can you downgrade it to 1.22 or 1.23 and check again ?
