### ISSUE TITLE
About landmarks

### ISSUE THREAD

**Issue by JasonAnn** [filby89/spectre#16]
Hi, thanks for the nice work!
I notice the landmarks are from Mesh verts, but I wonder how the landmarks index in the FLAME were got? And what are the differences between 'dynamic/static/full_lmk_faces_idx',  'dynamic/static/full_lmk_bary_coords' ?

Thanks

**Comment by filby89** [comment]
Hey,
thanks for your interest in SPECTRE. These landmarks are taken directly from FLAME. You can find how these were acquired in the ringnet paper https://arxiv.org/pdf/1905.06817.pdf (Section 3.4). You can find more info here as well:

https://github.com/Rubikplayer/flame-fitting/issues/40
