### ISSUE TITLE
Reconstructed mesh is not stable

### ISSUE THREAD

**Issue by limei1221** [filby89/spectre#20]
https://github.com/filby89/spectre/assets/21306360/d6589f90-1781-483f-a75b-3718f1fefe01

Hey I use your demo.py scripts run my video. Although the expressiveness and lip movement looks perfect the reconstructed face seems unstable, is there any way to solve this problem? Much appreciated!

**Comment by filby89** [comment]
Hi,
unfortunately this unstability comes from the pose/camera prediction which is taken from DECA:

https://github.com/yfeng95/DECA

In order to solve this you should check into retraining DECA to fix these pose issues or use another small network to regress on the pose/cam parameters.

**Comment by limei1221** [comment]
> Hi, unfortunately this unstability comes from the pose/camera prediction which is taken from DECA:
> 
> https://github.com/yfeng95/DECA
> 
> In order to solve this you should check into retraining DECA to fix these pose issues or use another small network to regress on the pose/cam parameters.

Thanks a lot for the reply! I'll try that and let you know.

**Comment by marcosMeng** [comment]
Have you already downloaded the  spectre_model. I am unable to download this model, counld you share this model with me?

**Comment by filby89** [comment]
Hey, the link for the model is:

https://drive.google.com/file/d/1vmWX6QmXGPnXTXWFgj67oHzOoOmxBh6B/view?usp=sharing

**Comment by xuduo18311199384** [comment]
Is there any way to optimize pose and reconstruct results?> small network to regress on the pose/cam parameters.

@limei1221

**Comment by filby89** [comment]
Hey, you can use SMIRK for that:

https://github.com/georgeretsi/smirk
