### ISSUE TITLE
Unable to download the pretrained SPECTRE model

### ISSUE THREAD

**Issue by EvelynQIN** [filby89/spectre#22]
Hello, I just ran the code you provided to download the pretrained SPRECTRE model, but got permission denied error, as follows. Could you please provide a new link?

```
gdown --id 1vmWX6QmXGPnXTXWFgj67oHzOoOmxBh6B
Permission denied: https://drive.google.com/uc?id=1vmWX6QmXGPnXTXWFgj67oHzOoOmxBh6B
Maybe you need to change permission over 'Anyone with the link'
```

**Comment by filby89** [comment]
Hey,
this may mean that Google Drive hit a daily bandwidth limit and it restricts download not directly from the website or that your gdown is an older version.
I just tested with gdown 5.2.0 and it worked (but it didnt with 4.7.1).
If it is still not downloading then you can try and download it directly from the website:

https://drive.google.com/file/d/1vmWX6QmXGPnXTXWFgj67oHzOoOmxBh6B/view?usp=drive_link
