### ISSUE TITLE
Maybe there is an error in the loss_indices calculation?

### ISSUE THREAD

**Issue by Koruvika** [filby89/spectre#25]
line 152 in trainer_spectre.py
![image](https://github.com/user-attachments/assets/b04fbc93-42a8-4e08-ac2e-a0f6c0f166d9)

In the paper, batch_size equals to 1. With that, loss_indices equals [], is there any mistakes here?

**Comment by filby89** [comment]
Hey,
if you check https://github.com/filby89/spectre/blob/master/src/trainer_spectre.py#L111 the original batch is 5 D:

1 x T x 3 x H x W

and then we resize it to:

T x 3 x H x W

so these loss indices actually show that the loss applies to all frames in the sequence but the first two and the last two !

**Comment by Koruvika** [comment]
Oh, my mistake, thanks for reply @filby89
