### ISSUE TITLE
couldn't download the spectre_model.tar

### ISSUE THREAD

**Issue by ujjawalcse** [filby89/spectre#5]
Hey @filby89 ,
I was trying to download the model but couldn't download it.
Getting the below error,

```
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
mv: cannot stat 'spectre_model.tar': No such file or directory
```
Can you please share the link here?
Thank you.

**Comment by filby89** [comment]
Hey,
I suspect it's a problem of gdown version. Can you try a newer version ? (e.g. 4.5.1). 
If you can't get it to work the model is here:
https://drive.google.com/file/d/1vmWX6QmXGPnXTXWFgj67oHzOoOmxBh6B/view?usp=sharing

**Comment by ujjawalcse** [comment]
Got it. 
Thanks for your immediate response @filby89
