### ISSUE TITLE
Question about saving the mesh

### ISSUE THREAD

**Issue by JSHZT** [filby89/spectre#6]
I tried to save the mesh using 'vert' with f of the 'head_template.obj', but my output is not the shape of a human head, where am I doing wrong, the ‘vert’ I use comes from the return of the 'decode()' function of the file 'spectre.py'

**Comment by JSHZT** [comment]
If I want to save the intermediate generated result, how can I do it

**Comment by filby89** [comment]
Hi,
yes you can use the 'verts' output in opdict to get the mesh. It should work. Note that you should not use the first 2 or last 2 indices of the video due the the temporal kernel of size 5. Can you share an example ?

**Comment by JSHZT** [comment]
Thanks! It work!
