### ISSUE TITLE
Great works! Do you try with temporal images rather than audio?

### ISSUE THREAD

**Issue by xiapengchng** [filby89/spectre#8]

**Comment by filby89** [comment]
Hi,
I'm not really sure what you mean. The method uses as input only a video without audio.

**Comment by xiapengchng** [comment]
Did you try to use the temporal constraint of video, like the consecuive T frames should have similar identity b and albedo alpha etc, since DECA and EMOCA only use single frames.

**Comment by filby89** [comment]
We only predict the expression coefficients in SPECTRE and get all other (including identity and albedo) from DECA. Thus, we do not use temporal constraints (since expressions are constantly changing in videos). However, we do use a window of 5 frames to get the prediction for the current frame.
